-- MySQL Script generated by MySQL Workbench
-- Sat Feb 22 14:32:35 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`brands`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`brands` ;

CREATE TABLE IF NOT EXISTS `mydb`.`brands` (
  `brand_id` VARCHAR(36) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`brand_id`),
  UNIQUE INDEX `brand_id_UNIQUE` (`brand_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`categories` ;

CREATE TABLE IF NOT EXISTS `mydb`.`categories` (
  `category_id` VARCHAR(36) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`category_id`),
  UNIQUE INDEX `category_id_UNIQUE` (`category_id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`suppliers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`suppliers` ;

CREATE TABLE IF NOT EXISTS `mydb`.`suppliers` (
  `supplier_id` VARCHAR(36) NOT NULL,
  `cod` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `document` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `phone` VARCHAR(12) NULL DEFAULT NULL,
  `created_at` DATE NULL,
  PRIMARY KEY (`supplier_id`),
  UNIQUE INDEX `supplier_id_UNIQUE` (`supplier_id` ASC) VISIBLE,
  UNIQUE INDEX `cod_UNIQUE` (`cod` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`products` ;

CREATE TABLE IF NOT EXISTS `mydb`.`products` (
  `product_id` VARCHAR(36) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `image` VARCHAR(100) NULL DEFAULT NULL,
  `brand_id` VARCHAR(36) NULL DEFAULT NULL,
  `category_id` VARCHAR(36) NULL DEFAULT NULL,
  `supplier_id` VARCHAR(36) NULL DEFAULT NULL,
  `quantity` INT NOT NULL,
  `quantity_min` INT NULL DEFAULT NULL,
  `price_cost` DECIMAL(10,2) NOT NULL,
  `selling_price` DECIMAL(10,2) NOT NULL,
  `validate_date` DATE NULL DEFAULT NULL,
  `created_at` DATETIME NULL,
  `status` ENUM("active", "inactive") NULL DEFAULT 'active',
  PRIMARY KEY (`product_id`),
  UNIQUE INDEX `product_id_UNIQUE` (`product_id` ASC) VISIBLE,
  INDEX `fk_product_brand_idx` (`brand_id` ASC) VISIBLE,
  INDEX `fk_product_category1_idx` (`category_id` ASC) VISIBLE,
  INDEX `fk_product_supplier1_idx` (`supplier_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_brand`
    FOREIGN KEY (`brand_id`)
    REFERENCES `mydb`.`brands` (`brand_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `mydb`.`categories` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_supplier1`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `mydb`.`suppliers` (`supplier_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`product_price_history`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`product_price_history` ;

CREATE TABLE IF NOT EXISTS `mydb`.`product_price_history` (
  `product_price_history_id` VARCHAR(36) NOT NULL,
  `product_id` VARCHAR(36) NOT NULL,
  `type` ENUM("cost", "selling") NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `created_at` DATETIME NULL,
  PRIMARY KEY (`product_price_history_id`),
  UNIQUE INDEX `product_price_history_id_UNIQUE` (`product_price_history_id` ASC) VISIBLE,
  INDEX `fk_product_price_history_products1_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_price_history_products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `mydb`.`products` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`stock_movements`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`stock_movements` ;

CREATE TABLE IF NOT EXISTS `mydb`.`stock_movements` (
  `stock_movement_id` VARCHAR(36) NOT NULL,
  `product_id` VARCHAR(36) NOT NULL,
  `quantity_changed` INT NOT NULL,
  `movement_type` INT NOT NULL,
  `date_moviment` DATE NOT NULL,
  `reason` VARCHAR(45) NULL DEFAULT NULL,
  `created_at` DATETIME NULL,
  PRIMARY KEY (`stock_movement_id`),
  UNIQUE INDEX `stock_movement_id_UNIQUE` (`stock_movement_id` ASC) VISIBLE,
  INDEX `fk_stock_movements_products1_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_stock_movements_products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `mydb`.`products` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `user_id` VARCHAR(36) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `tenant` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `tantant_UNIQUE` (`tenant` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`clients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`clients` ;

CREATE TABLE IF NOT EXISTS `mydb`.`clients` (
  `client_id` VARCHAR(36) NOT NULL,
  `cod` VARCHAR(9) NOT NULL,
  `name` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL DEFAULT NULL,
  `document` VARCHAR(20) NOT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `phone` VARCHAR(20) NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`client_id`),
  UNIQUE INDEX `client_id_UNIQUE` (`client_id` ASC) VISIBLE,
  UNIQUE INDEX `cod_UNIQUE` (`cod` ASC) VISIBLE,
  UNIQUE INDEX `document_UNIQUE` (`document` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cashier`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cashier` ;

CREATE TABLE IF NOT EXISTS `mydb`.`cashier` (
  `cashier_id` VARCHAR(36) NOT NULL,
  `opening_amount` DECIMAL(10,2) NOT NULL,
  `status` ENUM("opened", "closed") NOT NULL,
  `opened_at` DATETIME NULL,
  `closed_at` DATETIME NULL DEFAULT NULL,
  `user_opened_id` VARCHAR(36) NOT NULL,
  `user_closed_id` VARCHAR(36) NOT NULL,
  `total_sales` INT NULL DEFAULT NULL,
  `closing_amount` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`cashier_id`),
  UNIQUE INDEX `cashier_id_UNIQUE` (`cashier_id` ASC) VISIBLE,
  INDEX `fk_cashier_users1_idx` (`user_opened_id` ASC) VISIBLE,
  INDEX `fk_cashier_users2_idx` (`user_closed_id` ASC) VISIBLE,
  CONSTRAINT `fk_cashier_users1`
    FOREIGN KEY (`user_opened_id`)
    REFERENCES `mydb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cashier_users2`
    FOREIGN KEY (`user_closed_id`)
    REFERENCES `mydb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sales`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`sales` ;

CREATE TABLE IF NOT EXISTS `mydb`.`sales` (
  `sale_id` VARCHAR(36) NOT NULL,
  `user_id` VARCHAR(36) NOT NULL,
  `client_id` VARCHAR(36) NOT NULL,
  `cashier_id` VARCHAR(36) NOT NULL,
  `parcial_price` DECIMAL(10,2) NOT NULL,
  `total` DECIMAL(10,2) NOT NULL,
  `sale_date` DATE NOT NULL,
  `created_at` DATETIME NULL,
  PRIMARY KEY (`sale_id`),
  UNIQUE INDEX `saller_id_UNIQUE` (`sale_id` ASC) VISIBLE,
  INDEX `fk_sallers_users1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_sallers_clients1_idx` (`client_id` ASC) VISIBLE,
  INDEX `fk_sales_cashier1_idx` (`cashier_id` ASC) VISIBLE,
  CONSTRAINT `fk_sallers_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sallers_clients1`
    FOREIGN KEY (`client_id`)
    REFERENCES `mydb`.`clients` (`client_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sales_cashier1`
    FOREIGN KEY (`cashier_id`)
    REFERENCES `mydb`.`cashier` (`cashier_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sale_products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`sale_products` ;

CREATE TABLE IF NOT EXISTS `mydb`.`sale_products` (
  `sale_products_id` VARCHAR(36) NOT NULL,
  `sale_id` VARCHAR(36) NOT NULL,
  `product_name` VARCHAR(45) NOT NULL,
  `price_coust` DECIMAL(10,2) NOT NULL,
  `price_sale` DECIMAL(10,2) NOT NULL,
  `quantity` INT NOT NULL,
  `total_price` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`sale_products_id`),
  UNIQUE INDEX `idsale_products_UNIQUE` (`sale_products_id` ASC) VISIBLE,
  INDEX `fk_sale_products_sale1_idx` (`sale_id` ASC) VISIBLE,
  UNIQUE INDEX `sale_id_UNIQUE` (`sale_id` ASC) VISIBLE,
  CONSTRAINT `fk_sale_products_sale1`
    FOREIGN KEY (`sale_id`)
    REFERENCES `mydb`.`sales` (`sale_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cashier_moviments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cashier_moviments` ;

CREATE TABLE IF NOT EXISTS `mydb`.`cashier_moviments` (
  `cashier_moviment_id` VARCHAR(36) NOT NULL,
  `cashier_id` VARCHAR(36) NOT NULL,
  `user_id` VARCHAR(36) NOT NULL,
  `type` ENUM("in", "out") NOT NULL,
  `amount` DOUBLE(10,2) NOT NULL,
  `reason` VARCHAR(255) NULL DEFAULT NULL,
  `date` DATE NOT NULL,
  PRIMARY KEY (`cashier_moviment_id`),
  UNIQUE INDEX `cashier_moviment_id_UNIQUE` (`cashier_moviment_id` ASC) VISIBLE,
  INDEX `fk_cashier_moviments_cashier1_idx` (`cashier_id` ASC) VISIBLE,
  INDEX `fk_cashier_moviments_users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_cashier_moviments_cashier1`
    FOREIGN KEY (`cashier_id`)
    REFERENCES `mydb`.`cashier` (`cashier_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cashier_moviments_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`shopping`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`shopping` ;

CREATE TABLE IF NOT EXISTS `mydb`.`shopping` (
  `shopping_id` VARCHAR(36) NOT NULL,
  `supplier_id` VARCHAR(36) NOT NULL,
  `product_id` VARCHAR(36) NOT NULL,
  `price_cost` DECIMAL(10,2) NOT NULL,
  `quantity` INT NOT NULL,
  `created_at` DATETIME NULL DEFAULT DATETIME(),
  PRIMARY KEY (`shopping_id`),
  UNIQUE INDEX `shopping_id_UNIQUE` (`shopping_id` ASC) VISIBLE,
  INDEX `fk_shopping_suppliers1_idx` (`supplier_id` ASC) VISIBLE,
  INDEX `fk_shopping_products1_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_shopping_suppliers1`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `mydb`.`suppliers` (`supplier_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_shopping_products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `mydb`.`products` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`enterprises`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`enterprises` ;

CREATE TABLE IF NOT EXISTS `mydb`.`enterprises` (
  `enterprise_id` VARCHAR(36) NOT NULL,
  `user_id` VARCHAR(36) NOT NULL,
  `logo` VARCHAR(255) NULL DEFAULT NULL,
  `document` VARCHAR(20) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`enterprise_id`),
  UNIQUE INDEX `enterprise_id_UNIQUE` (`enterprise_id` ASC) VISIBLE,
  INDEX `fk_enterprises_users1_idx` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `document_UNIQUE` (`document` ASC) VISIBLE,
  CONSTRAINT `fk_enterprises_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`addresses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`addresses` ;

CREATE TABLE IF NOT EXISTS `mydb`.`addresses` (
  `address_id` VARCHAR(36) NOT NULL,
  `entity_id` VARCHAR(36) NOT NULL,
  `street` VARCHAR(45) NOT NULL,
  `number` INT NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `state` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NULL DEFAULT 'DEFAULT \'Brasil\'',
  `postal_code` VARCHAR(15) NULL DEFAULT NULL,
  `complement` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` DATETIME NULL,
  PRIMARY KEY (`address_id`),
  UNIQUE INDEX `enterprise_address_id_UNIQUE` (`address_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`enterprise_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`enterprise_users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`enterprise_users` (
  `identerprise_user_id` VARCHAR(36) NOT NULL,
  `user_id` VARCHAR(36) NOT NULL,
  `enterprise_id` VARCHAR(36) NOT NULL,
  `role` ENUM("owner", "manager", "employee") NOT NULL,
  `created_at` DATETIME NULL,
  PRIMARY KEY (`identerprise_user_id`),
  UNIQUE INDEX `identerprise_user_id_UNIQUE` (`identerprise_user_id` ASC) VISIBLE,
  INDEX `fk_enterprise_users_users1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_enterprise_users_enterprises1_idx` (`enterprise_id` ASC) VISIBLE,
  CONSTRAINT `fk_enterprise_users_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_enterprise_users_enterprises1`
    FOREIGN KEY (`enterprise_id`)
    REFERENCES `mydb`.`enterprises` (`enterprise_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`permissions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`permissions` ;

CREATE TABLE IF NOT EXISTS `mydb`.`permissions` (
  `permission_id` VARCHAR(36) NOT NULL,
  `type` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`permission_id`),
  UNIQUE INDEX `idpermission_id_UNIQUE` (`permission_id` ASC) VISIBLE,
  UNIQUE INDEX `type_UNIQUE` (`type` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_permissions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user_permissions` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user_permissions` (
  `user_permission_id` VARCHAR(36) NOT NULL,
  `user_id` VARCHAR(36) NOT NULL,
  `permission_id` VARCHAR(36) NOT NULL,
  `granted_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_permission_id`),
  UNIQUE INDEX `user_permission_id_UNIQUE` (`user_permission_id` ASC) VISIBLE,
  INDEX `fk_user_permissions_users1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_user_permissions_permissions1_idx` (`permission_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_permissions_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_permissions_permissions1`
    FOREIGN KEY (`permission_id`)
    REFERENCES `mydb`.`permissions` (`permission_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
